# Generated by Django 6.0.3 on 2026-04-05 19:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('renagro_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('technical_specifications', models.TextField(blank=True, null=True)),
                ('usage_purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'machines',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.TextField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Postings',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('availability_start', models.DateTimeField(blank=True, null=True)),
                ('availability_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.machines')),
            ],
            options={
                'db_table': 'postings',
            },
        ),
        migrations.CreateModel(
            name='PostingsPhotos',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=1024)),
                ('is_primary', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('postings', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.postings')),
            ],
            options={
                'db_table': 'postings_photos',
            },
        ),
        migrations.CreateModel(
            name='Rentals',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('initial_hour_meter', models.IntegerField(blank=True, null=True)),
                ('final_hour_meter', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('postings', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.postings')),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rentals_operator_set', to='api.users')),
            ],
            options={
                'db_table': 'rentals',
            },
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('document_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('accepted_by_lessor', models.BooleanField(blank=True, null=True)),
                ('accepted_by_lessee', models.BooleanField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('rental', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.rentals')),
            ],
            options={
                'db_table': 'contracts',
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_for_moderation', models.BooleanField(blank=True, null=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.rentals')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages_receiver_set', to='api.users')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.AddField(
            model_name='machines',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users'),
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('type', models.TextField()),
                ('document_number', models.CharField(blank=True, max_length=50, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('file_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users')),
            ],
            options={
                'db_table': 'credentials',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.rentals')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews_reviewee_set', to='api.users')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.users')),
            ],
            options={
                'db_table': 'reviews',
                'unique_together': {('rental', 'reviewer')},
            },
        ),
    ]
