# Generated by Django 6.0.3 on 2026-05-24 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
