# Generated by Django 6.0.3 on 2026-08-26 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



APPEND_ONLY_UP = """
CREATE OR REPLACE FUNCTION contract_signatures_append_only()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION
        'contract_signatures e append-only: registros de assinatura nao podem ser alterados ou removidos';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER contract_signatures_no_update
    BEFORE UPDATE ON contract_signatures
    FOR EACH ROW EXECUTE FUNCTION contract_signatures_append_only();

CREATE TRIGGER contract_signatures_no_delete
    BEFORE DELETE ON contract_signatures
    FOR EACH ROW EXECUTE FUNCTION contract_signatures_append_only();
"""

APPEND_ONLY_DOWN = """
DROP TRIGGER IF EXISTS contract_signatures_no_update ON contract_signatures;
DROP TRIGGER IF EXISTS contract_signatures_no_delete ON contract_signatures;
DROP FUNCTION IF EXISTS contract_signatures_append_only();
"""


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContractSignatureOtps",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("role", models.CharField(max_length=20)),
                ("email", models.CharField(max_length=255)),
                ("code_hash", models.CharField(max_length=64)),
                ("attempts", models.IntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="signature_otps",
                        to="api.contracts",
                    ),
                ),
            ],
            options={
                "db_table": "contract_signature_otps",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["contract", "role", "-created_at"],
                        name="contract_si_contrac_fcb9f7_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContractSignatures",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("signer_name", models.CharField(blank=True, max_length=255)),
                ("signer_email", models.CharField(blank=True, max_length=255)),
                ("role", models.CharField(max_length=20)),
                ("document_version", models.CharField(blank=True, max_length=20)),
                ("document_hash", models.CharField(max_length=64)),
                ("hash_algorithm", models.CharField(default="sha256", max_length=20)),
                ("signed_at", models.DateTimeField()),
                ("ip_address", models.CharField(blank=True, max_length=64)),
                ("user_agent", models.CharField(blank=True, max_length=1024)),
                ("otp_verified", models.BooleanField(default=False)),
                ("previous_hash", models.CharField(max_length=64)),
                ("record_hash", models.CharField(max_length=64, unique=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="signatures",
                        to="api.contracts",
                    ),
                ),
                (
                    "signer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "contract_signatures",
                "ordering": ["signed_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["contract", "signed_at"],
                        name="contract_si_contrac_aabd44_idx",
                    )
                ],
            },
        ),
        migrations.RunSQL(APPEND_ONLY_UP, reverse_sql=APPEND_ONLY_DOWN),
    ]
