# Generated by Django 6.0.3 on 2026-04-05 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password_hash',
            new_name='password',
        ),
    ]
