# Generated by Django 6.0.3 on 2026-05-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passwordresets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresets',
            name='user',
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
        migrations.DeleteModel(
            name='PasswordResets',
        ),
    ]
