# Generated by Django 6.0.3 on 2026-04-12 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_password_hash_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
    ]
