# Generated by Django 6.0.3 on 2026-04-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='birth_date',
            field=models.DateField(default='2000-05-05'),
            preserve_default=False,
        ),
    ]
