# Generated by Django 6.0.3 on 2026-04-13 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_users_last_login_alter_users_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
