# Generated by Django 6.0.3 on 2026-05-24 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postings',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('location_address', models.TextField(blank=True, null=True)),
                ('availability_start', models.DateTimeField(blank=True, null=True)),
                ('availability_end', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('machinery', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='machines.machines')),
            ],
            options={
                'db_table': 'postings',
            },
        ),
        migrations.CreateModel(
            name='PostingsPhotos',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=1024)),
                ('is_primary', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('postings', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='postings.postings')),
            ],
            options={
                'db_table': 'postings_photos',
            },
        ),
    ]
