# Generated by Django 6.0.3 on 2026-08-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postings",
            name="location_cep",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
