# Generated by Django 6.0.3 on 2026-08-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postings", "0002_postings_location_cep"),
    ]

    operations = [
        migrations.AddField(
            model_name="postings",
            name="max_reservation_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
