# Generated by Django 6.0.3 on 2026-05-31 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_validation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('issuing_organization', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('issue_date', models.DateField()),
                ('credential_code', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('media_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certifications',
            },
        ),
        migrations.CreateModel(
            name='OperatorLicense',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=255)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(max_length=100)),
                ('birth_place', models.CharField(max_length=255)),
                ('renach_number', models.CharField(max_length=11)),
                ('cnh_number', models.CharField(max_length=11)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('AB', 'Ab'), ('AC', 'Ac'), ('AD', 'Ad'), ('AE', 'Ae')], max_length=2)),
                ('first_license_date', models.DateField()),
                ('issue_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('issuing_state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('issuing_authority', models.CharField(max_length=255)),
                ('situation', models.CharField(choices=[('active', 'Ativa'), ('expired', 'Vencida'), ('suspended', 'Suspensa'), ('revoked', 'Cassada'), ('blocked', 'Bloqueada'), ('ppd', 'PPD')], max_length=20)),
                ('acc', models.BooleanField(default=False)),
                ('ear', models.BooleanField(default=False)),
                ('medical_restrictions', models.TextField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('file_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('validation_status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operator_licenses',
            },
        ),
        migrations.DeleteModel(
            name='Credentials',
        ),
    ]
