# Generated by Django 6.0.3 on 2026-05-31 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_validation', '0002_certification_operatorlicense_delete_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='operatorlicense',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('AB', 'AB'), ('AC', 'AC'), ('AD', 'AD'), ('AE', 'AE')], max_length=2),
        ),
        migrations.AlterField(
            model_name='operatorlicense',
            name='issuing_state',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='operatorlicense',
            name='situation',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('blocked', 'Blocked'), ('ppd', 'Ppd')], max_length=20),
        ),
        migrations.AlterField(
            model_name='operatorlicense',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
