# Generated by Django 6.0.3 on 2026-05-31 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_validation', '0003_alter_certification_validation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatorlicense',
            name='renach_number',
        ),
    ]
