# Generated by Django 6.0.3 on 2026-05-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_validation', '0004_remove_operatorlicense_renach_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
