# Generated by Django 6.0.3 on 2026-06-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_validation', '0005_certification_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operatorlicense',
            name='review_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
