# Generated by Django 6.0.3 on 2026-09-02 03:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_move_messages_to_chat_app"),
        ("chat", "0001_initial"),
        ("postings", "0003_postings_max_reservation_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Backfill ANTES de apertar para NOT NULL. sent_at nulo quebraria a
        # paginacao por keyset em (sent_at, id); flagged nulo quebraria o
        # indice parcial da fila de moderacao.
        migrations.RunSQL(
            "UPDATE messages SET sent_at = COALESCE(sent_at, CURRENT_TIMESTAMP) WHERE sent_at IS NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE messages SET flagged_for_moderation = COALESCE(flagged_for_moderation, false) "
            "WHERE flagged_for_moderation IS NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Substituido pelo composto idx_messages_rental_thread.
        migrations.RunSQL(
            "DROP INDEX IF EXISTS idx_messages_rental_id",
            reverse_sql="CREATE INDEX IF NOT EXISTS idx_messages_rental_id ON messages(rental_id)",
        ),
        migrations.CreateModel(
            name="MessageReports",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField()),
                (
                    "resolution",
                    models.CharField(
                        blank=True,
                        choices=[("dismissed", "Arquivada"), ("upheld", "Procedente")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("resolution_note", models.TextField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "message_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="messages",
            name="client_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messages",
            name="hidden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="messages",
            name="posting",
            field=models.ForeignKey(
                blank=True,
                db_column="posting_id",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="messages",
                to="postings.postings",
            ),
        ),
        migrations.AddField(
            model_name="messages",
            name="read_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="messages",
            name="flagged_for_moderation",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="messages",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="rental",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="api.rentals",
            ),
        ),
        migrations.AlterField(
            model_name="messages",
            name="sent_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name="messages",
            index=models.Index(
                fields=["rental", "-sent_at", "-id"], name="idx_messages_rental_thread"
            ),
        ),
        migrations.AddIndex(
            model_name="messages",
            index=models.Index(
                fields=["posting", "-sent_at", "-id"],
                name="idx_messages_posting_thread",
            ),
        ),
        migrations.AddIndex(
            model_name="messages",
            index=models.Index(
                fields=["sender", "-sent_at"], name="idx_messages_sender_recent"
            ),
        ),
        migrations.AddIndex(
            model_name="messages",
            index=models.Index(
                fields=["receiver", "-sent_at"], name="idx_messages_receiver_recent"
            ),
        ),
        migrations.AddIndex(
            model_name="messages",
            index=models.Index(
                condition=models.Q(("read_at__isnull", True)),
                fields=["receiver"],
                name="idx_messages_unread",
            ),
        ),
        migrations.AddIndex(
            model_name="messages",
            index=models.Index(
                condition=models.Q(("flagged_for_moderation", True)),
                fields=["-sent_at"],
                name="idx_messages_flagged",
            ),
        ),
        migrations.AddConstraint(
            model_name="messages",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("posting__isnull", True), ("rental__isnull", False)),
                    models.Q(("posting__isnull", False), ("rental__isnull", True)),
                    _connector="OR",
                ),
                name="messages_exactly_one_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="messages",
            constraint=models.UniqueConstraint(
                condition=models.Q(("client_id__isnull", False)),
                fields=("sender", "client_id"),
                name="messages_sender_client_id_uniq",
            ),
        ),
        migrations.AddField(
            model_name="messagereports",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="chat.messages",
            ),
        ),
        migrations.AddField(
            model_name="messagereports",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagereports",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="message_report_resolutions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="messagereports",
            constraint=models.UniqueConstraint(
                fields=("message", "reported_by"),
                name="message_reports_unique_reporter",
            ),
        ),
    ]
