"""
Django settings for djangoapi project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(dotenv_path=str(BASE_DIR / '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--rxohg4%^v8&aj58z)v+*)_ry)d9rhf@s&wearauq4hdt#7kp1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
    'users',
    'authentication',
    'postings',
    'machines',
    'administration',
    'document_validation',
    'drf_spectacular',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # Add this at the VERY TOP
    'django.middleware.common.CommonMiddleware', # Must be after CorsMiddleware
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Only allow your specific frontend URL
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:5174",
    "http://127.0.0.1:5174",
]

# If you want to allow cookies/sessions to be sent (like for login)
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'djangoapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoapi.wsgi.application'

AUTH_USER_MODEL = 'users.Users'

## SETTING THE AUTHENTICATION

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework.authentication.BasicAuthentication', ## removed cuz not needed
        'rest_framework.authentication.SessionAuthentication',
        'authentication.extensions.authentication.AppJWTAuthentication',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Frota Rural API',
    'DESCRIPTION': (
        'Documentação completa e interativa da API do Frota Rural. Uma plataforma focada na '
        'conexão entre Locadores de Maquinário Agrícola e Locatários (Produtores Rurais).\n\n'
        '## Autenticação\n\n'
        'A API usa **JWT (Bearer token)**. Para testar os endpoints protegidos por aqui:\n\n'
        '1. Chame `POST /api/login` com e-mail e senha.\n'
        '2. Copie o valor de `access` da resposta.\n'
        '3. Clique em **Authorize** (canto superior direito) e cole o token.\n\n'
        'O token de acesso expira em 15 minutos; use `POST /api/login/refresh` para renová-lo.'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'CONTACT': {'name': 'Equipe Frota Rural', 'url': 'https://github.com/joaoson/Frota_Rural'},
    'SERVERS': [
        {'url': 'http://127.0.0.1:8000', 'description': 'Ambiente local de desenvolvimento'},
    ],
    'SORT_OPERATIONS': False,
    # `validation_status` aparece com dois conjuntos de opções: o do model (inclui
    # `pending`) e o da decisão do administrador. Sem os nomes explícitos o
    # drf-spectacular gera componentes com sufixo aleatório (ValidationStatusDe3Enum).
    'ENUM_NAME_OVERRIDES': {
        'ValidationStatusEnum': 'document_validation.serializer.VALIDATION_STATUS_CHOICES',
        'ReviewDecisionEnum': 'document_validation.serializer.REVIEW_DECISION_CHOICES',
    },
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'displayRequestDuration': True,
        'docExpansion': 'none',
        'filter': True,
    },
    # Ordem em que os grupos aparecem no Swagger UI. Cada view declara sua tag
    # via `@extend_schema(tags=[...])`; sem isso o drf-spectacular agruparia
    # tudo sob o primeiro segmento do path ('api').
    'TAGS': [
        {'name': 'Autenticação', 'description': 'Login, refresh, logout e recuperação de senha.'},
        {'name': 'Usuários', 'description': 'Cadastro, consulta e manutenção de contas.'},
        {'name': 'Maquinário', 'description': 'Equipamentos cadastrados pelos locadores.'},
        {'name': 'Anúncios', 'description': 'Publicação de maquinário disponível para locação.'},
        {'name': 'Locações', 'description': 'Reservas e ciclo de vida das locações.'},
        {'name': 'Contratos', 'description': 'Geração e assinatura dos contratos de locação.'},
        {'name': 'Avaliações', 'description': 'Reputação de locadores e locatários.'},
        {'name': 'Documentos', 'description': 'CNHs, certificações e validação por Machine Learning.'},
        {'name': 'Administração', 'description': 'Moderação de usuários e anúncios.'},
    ],
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'CHECK_USER_IS_ACTIVE': False,  # Users model has no is_active field
}

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

## THIS NEEDS CHANGING DEPENDING ON YOUR LOCAL INSTACE OF POSTGRESQL
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get('DB_NAME'),
        "USER": os.environ.get('DB_USER', 'postgres'),
        "PASSWORD": os.environ.get('DB_PASSWORD'),
        "HOST": os.environ.get('DB_HOST', 'localhost'),
        "PORT": os.environ.get('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Password Reset
PASSWORD_RESET_TIMEOUT = 3600

FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173')

# Resend (transactional email)
RESEND_API_KEY = os.getenv('RESEND_API_KEY', '')
RESEND_SUPPORT_EMAIL = os.getenv('RESEND_SUPPORT_EMAIL', 'onboarding@resend.dev')
