export type OperatorLicense = {
  id: string;
  user: string;
  name: string;
  birth_date: string;
  cpf: string;
  rg: string;
  mother_name: string;
  father_name?: string | null;
  nationality: string;
  birth_place: string;
  cnh_number: string;
  category: string;
  first_license_date: string;
  issue_date: string;
  expiration_date: string;
  issuing_state: string;
  issuing_authority: string;
  situation: string;
  acc: boolean;
  ear: boolean;
  medical_restrictions?: string | null;
  observations?: string | null;
  points: number;
  file_url?: string | null;
  validation_status: string;
  review_note?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
};
