# Generated by Django 6.0.3 on 2026-06-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="cep",
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
