# Generated by Django 6.0.3 on 2026-08-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_users_cep"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="users",
            name="state",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
