name: Convert Docx to PDF

on:
  push:
    branches-ignore: [ main ]

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install LibreOffice
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice

      - name: Run Conversion
        run: |
          soffice --headless --convert-to pdf \
            "BSI-Especificação do Projeto-Frota Rural.docx" \
            --outdir .

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BSI-Especificacao-do-Projeto-Frota-Rural
          path: "BSI-Especificação do Projeto-Frota Rural.pdf"