name: Convert Docx to PDF

on:
  push:
    branches-ignore: [ main ]

permissions:
  contents: write

jobs:
  convert_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install LibreOffice
        run: |
          sudo apt-get update
          sudo apt-get install -y libreoffice

      - name: Run Conversion
        run: |
          soffice --headless --convert-to pdf \
            "BSI-Especificação do Projeto-Frota Rural.docx" \
            --outdir .

      - name: Commit and Push to current branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git checkout ${{ github.head_ref }}
          git pull --rebase origin ${{ github.head_ref }}
          git add "BSI-Especificação do Projeto-Frota Rural.pdf"
          git commit -m "docs: auto-generate PDF from docx" || true
          git push origin HEAD:${{ github.head_ref }}